// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#include "src/ate/ate_perso_blob.h"

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include "absl/log/log.h"
#include "src/ate/ate_api.h"

// Helper to read the object header.
void ReadObjectHeader(const uint8_t* buf, size_t remaining, int blob_version,
                      uint32_t* obj_size, uint32_t* obj_type,
                      size_t* header_size) {
  if (blob_version == 2) {
    uint32_t hdr_val =
        __builtin_bswap32(*reinterpret_cast<const uint32_t*>(buf));
    *obj_size = hdr_val & 0xFFFFFF;
    *obj_type = (hdr_val >> 24) & 0xFF;
    *header_size = 4;
  } else {  // V1 Legacy
    uint16_t hdr_val =
        __builtin_bswap16(*reinterpret_cast<const uint16_t*>(buf));
    *obj_size = hdr_val & 0xFFF;
    *obj_type = (hdr_val >> 12) & 0xF;
    *header_size = 2;
  }
}

// Checks if a blob was generated by a legacy V1 firmware by examining the
// first object.
DLLEXPORT bool IsLegacyV1Blob(const uint8_t* body, size_t size) {
  if (size < 2) return false;
  uint16_t hdr_val =
      __builtin_bswap16(*reinterpret_cast<const uint16_t*>(body));

  // If it's a V2 blob (starts with Type 15), it is NOT a legacy V1 blob.
  return (hdr_val >> 12) != kPersoObjectTypeBlobVersion;
}

// Determines the blob format version.
int GetBlobVersion(const uint8_t* body, size_t size) {
  if (size < 2) return 0;
  uint16_t hdr_val =
      __builtin_bswap16(*reinterpret_cast<const uint16_t*>(body));
  if ((hdr_val >> 12) == kPersoObjectTypeBlobVersion) return 2;
  return IsLegacyV1Blob(body, size) ? 1 : 0;
}

// Helper function to extract a certificate from a perso blob.
int ExtractCertObject(const uint8_t* buf, size_t buf_size, int blob_version,
                      perso_tlv_cert_obj_t* cert_obj) {
  if (buf == nullptr || cert_obj == nullptr) {
    LOG(ERROR) << "Invalid input buffer or cert_obj pointer";
    return -1;
  }

  uint32_t obj_size;
  uint32_t obj_type;
  size_t header_size;
  ReadObjectHeader(buf, buf_size, blob_version, &obj_size, &obj_type,
                   &header_size);

  if (obj_size == 0 || obj_size > buf_size) {
    LOG(ERROR) << "Invalid object size: " << obj_size
               << ", buffer size: " << buf_size;
    return -1;
  }
  if (obj_type != kPersoObjectTypeX509Tbs &&
      obj_type != kPersoObjectTypeX509Cert &&
      obj_type != kPersoObjectTypeCwtCert) {
    LOG(ERROR) << "Invalid object type: " << obj_type
               << ", expected X509 TBS or (full) cert";
    return -1;
  }

  buf += header_size;
  buf_size -= header_size;

  uint32_t name_len;
  uint32_t cert_entry_size;
  size_t cert_header_size;

  if (blob_version == 2) {
    if (buf_size < 4) return -1;
    uint32_t crth_val =
        __builtin_bswap32(*reinterpret_cast<const uint32_t*>(buf));
    cert_entry_size = crth_val & 0xFFFFFF;
    name_len = (crth_val >> 24) & 0xFF;
    cert_header_size = 4;
  } else {
    if (buf_size < 2) return -1;
    uint16_t crth_val =
        __builtin_bswap16(*reinterpret_cast<const uint16_t*>(buf));
    cert_entry_size = crth_val & 0xFFF;
    name_len = (crth_val >> 12) & 0xF;
    cert_header_size = 2;
  }

  buf += cert_header_size;
  buf_size -= cert_header_size;

  if (buf_size < name_len) {
    LOG(ERROR) << "Buffer too small for certificate name: " << name_len
               << ", available: " << buf_size;
    return -1;
  }

  memcpy(cert_obj->name, buf, name_len);
  cert_obj->name[name_len] = '\0';

  buf += name_len;
  buf_size -= name_len;

  uint32_t cert_body_size = cert_entry_size - name_len - cert_header_size;
  if (cert_body_size > buf_size) {
    LOG(ERROR) << "Certificate body size exceeds available buffer size: "
               << cert_body_size << " > " << buf_size;
    return -1;
  }

  cert_obj->cert_body_p = reinterpret_cast<const char*>(buf);
  cert_obj->cert_body_size = cert_body_size;

  return 0;
}

// Helper function to extract a TBS certificate from a perso blob.
int PackX509TbsCertStruct(const perso_tlv_cert_obj_t* cert_obj,
                          endorse_cert_request_t* tbs_cert) {
  if (cert_obj == nullptr || tbs_cert == nullptr) {
    LOG(ERROR) << "Invalid cert_obj or tbs_cert object pointer.";
    return -1;
  }

  // Copy the certificate body.
  if (cert_obj->cert_body_size > kCertificateMaxSize) {
    LOG(ERROR) << "TBS certificate body size exceeds maximum: "
               << cert_obj->cert_body_size << " > " << kCertificateMaxSize;
    return -1;
  }
  memset(tbs_cert->tbs, 0, sizeof(tbs_cert->tbs));
  memcpy(tbs_cert->tbs, cert_obj->cert_body_p, cert_obj->cert_body_size);
  tbs_cert->tbs_size = cert_obj->cert_body_size;

  // Copy the key label.
  size_t key_label_size = strlen(cert_obj->name);
  if (key_label_size > kCertificateKeyLabelMaxSize) {
    LOG(ERROR) << "Key label size exceeds maximum: " << key_label_size << " > "
               << kCertificateKeyLabelMaxSize;
    return -1;
  }
  memset(tbs_cert->key_label, 0, sizeof(tbs_cert->key_label));
  memcpy(tbs_cert->key_label, cert_obj->name, key_label_size);
  tbs_cert->key_label_size = key_label_size;

  tbs_cert->hash_type = kHashTypeSha256;
  tbs_cert->curve_type = kCurveTypeP256;
  tbs_cert->signature_encoding = kSignatureEncodingDer;

  return 0;
}

// Helper function to extract a (fully formed) certificate from a perso blob.
int PackCertStruct(const perso_tlv_cert_obj_t* cert_obj, uint16_t cert_type,
                   endorse_cert_response_t* cert) {
  if (cert_obj == nullptr || cert == nullptr) {
    LOG(ERROR) << "Invalid cert_obj or cert object pointer.";
    return -1;
  }
  if (cert_type != kPersoObjectTypeX509Cert &&
      cert_type != kPersoObjectTypeCwtCert) {
    LOG(ERROR) << "Invalid cert type.";
    return -1;
  }

  // Set the cert type.
  if (cert_type == kPersoObjectTypeCwtCert) {
    cert->type = kCertTypeCwt;
  } else {
    cert->type = kCertTypeX509;
  }

  // Copy the certificate body.
  if (cert_obj->cert_body_size > kCertificateMaxSize) {
    LOG(ERROR) << "Certificate body size exceeds maximum: "
               << cert_obj->cert_body_size << " > " << kCertificateMaxSize;
    return -1;
  }
  memset(cert->cert, 0, sizeof(cert->cert));
  memcpy(cert->cert, cert_obj->cert_body_p, cert_obj->cert_body_size);
  cert->cert_size = cert_obj->cert_body_size;

  // Copy the key label.
  size_t key_label_size = strlen(cert_obj->name);
  if (key_label_size > kCertificateKeyLabelMaxSize) {
    LOG(ERROR) << "Key label size exceeds maximum: " << key_label_size << " > "
               << kCertificateKeyLabelMaxSize;
    return -1;
  }
  memset(cert->key_label, 0, sizeof(cert->key_label));
  memcpy(cert->key_label, cert_obj->name, key_label_size);
  cert->key_label_size = key_label_size;

  return 0;
}

// Helper function to extract a device ID from a perso blob.
int ExtractDeviceId(const uint8_t* buf, size_t buf_size, int blob_version,
                    device_id_bytes_t* device_id) {
  if (buf == nullptr || device_id == nullptr) {
    LOG(ERROR) << "Invalid input buffer or device ID pointer";
    return -1;
  }

  uint32_t obj_size;
  uint32_t obj_type;
  size_t header_size;
  ReadObjectHeader(buf, buf_size, blob_version, &obj_size, &obj_type,
                   &header_size);

  if (obj_type == kPersoObjectTypeDeviceId) {
    if (obj_size != sizeof(device_id_bytes_t) + header_size) {
      LOG(ERROR) << "Invalid device ID object size: " << obj_size
                 << ", expected: " << (sizeof(device_id_bytes_t) + header_size);
      return -1;
    }
    memcpy(device_id->raw, buf + header_size, sizeof(device_id_bytes_t));
    return 0;
  }
  LOG(ERROR) << "Invalid object type for device ID: " << obj_type
             << ", expected: " << kPersoObjectTypeDeviceId;
  return -1;
}

// Helper function to pack a certificate object into a perso blob.
int PackCertTlvObject(const endorse_cert_response_t* cert, int blob_version,
                      perso_blob_t* blob) {
  // Calculate the size of the object header and certificate header.
  size_t cert_header_size = (blob_version == 2) ? 4 : 2;
  size_t cert_entry_size =
      cert_header_size + cert->key_label_size + cert->cert_size;

  uint16_t type = (cert->type == kCertTypeCwt) ? kPersoObjectTypeCwtCert
                                               : kPersoObjectTypeX509Cert;
  size_t header_size = (blob_version == 2) ? 4 : 2;
  size_t obj_size = header_size + cert_entry_size;

  if (blob->next_free + obj_size > sizeof(blob->body)) {
    LOG(ERROR) << "Personalization blob is full, cannot add more objects.";
    return -1;
  }

  // Set up the object header.
  uint8_t* buf = blob->body + blob->next_free;
  if (blob_version == 2) {
    uint32_t header = (((uint32_t)type) << 24) | (obj_size & 0xFFFFFF);
    *reinterpret_cast<uint32_t*>(buf) = __builtin_bswap32(header);
  } else {
    uint16_t header = (type << 12) | (obj_size & 0xFFF);
    *reinterpret_cast<uint16_t*>(buf) = __builtin_bswap16(header);
  }

  // Set up the certificate header.
  buf += header_size;
  if (blob_version == 2) {
    uint32_t crth = (((uint32_t)cert->key_label_size & 0xFF) << 24) |
                    (cert_entry_size & 0xFFFFFF);
    *reinterpret_cast<uint32_t*>(buf) = __builtin_bswap32(crth);
  } else {
    uint16_t crth = (((uint16_t)cert->key_label_size & 0xF) << 12) |
                    (cert_entry_size & 0xFFF);
    *reinterpret_cast<uint16_t*>(buf) = __builtin_bswap16(crth);
  }

  // Copy the certificate name string.
  buf += cert_header_size;
  memcpy(buf, cert->key_label, cert->key_label_size);

  // Copy the certificate data.
  buf += cert->key_label_size;
  memcpy(buf, cert->cert, cert->cert_size);

  // Update the next free offset in the blob.
  blob->next_free += obj_size;
  blob->num_objects++;

  return 0;
}

// Helper function to pack a seed object into a perso blob.
int PackSeedTlvObject(const seed_t* seed, int blob_version,
                      perso_blob_t* blob) {
  size_t header_size = (blob_version == 2) ? 4 : 2;
  size_t obj_size = header_size + seed->size;
  if (blob->next_free + obj_size > sizeof(blob->body)) {
    LOG(ERROR) << "Personalization blob is full, cannot add more objects.";
    return -1;
  }

  // Set up the object header.
  uint8_t* buf = blob->body + blob->next_free;
  if (blob_version == 2) {
    uint32_t header = (((uint32_t)seed->type) << 24) | (obj_size & 0xFFFFFF);
    *reinterpret_cast<uint32_t*>(buf) = __builtin_bswap32(header);
  } else {
    uint16_t header = (seed->type << 12) | (obj_size & 0xFFF);
    *reinterpret_cast<uint16_t*>(buf) = __builtin_bswap16(header);
  }

  // Copy the certificate data.
  buf += header_size;
  memcpy(buf, seed->raw, seed->size);

  // Update the next free offset in the blob.
  blob->next_free += obj_size;
  blob->num_objects++;

  return 0;
}

DLLEXPORT int UnpackPersoBlob(
    const perso_blob_t* blob, device_id_bytes_t* device_id,
    endorse_cert_signature_t* signature, sha256_hash_t* perso_fw_hash,
    endorse_cert_request_t* tbs_certs, size_t* tbs_cert_count,
    endorse_cert_response_t* certs, size_t* cert_count, seed_t* seeds,
    size_t* seed_count) {
  if (device_id == nullptr || signature == nullptr ||
      perso_fw_hash == nullptr || tbs_certs == nullptr ||
      tbs_cert_count == nullptr || certs == nullptr || cert_count == nullptr ||
      seeds == nullptr || seed_count == nullptr) {
    LOG(ERROR) << "Invalid output parameters";
    return -1;
  }

  if (blob == nullptr || blob->next_free == 0) {
    LOG(ERROR) << "Invalid personalization blob";
    return -1;  // Invalid blob
  }

  memset(device_id->raw, 0, sizeof(device_id_bytes_t));
  memset(signature->raw, 0, sizeof(endorse_cert_signature_t));
  memset(perso_fw_hash->raw, 0, sizeof(sha256_hash_t));

  *tbs_cert_count = 0;
  *cert_count = 0;
  size_t max_seed_count = *seed_count;
  *seed_count = 0;

  const uint8_t* buf = blob->body;
  size_t remaining = blob->next_free;

  if (remaining > sizeof(blob->body)) {
    LOG(ERROR) << "Remaining buffer size exceeds maximum allowed: " << remaining
               << " > " << sizeof(blob->body);
    return -1;
  }

  int blob_version = GetBlobVersion(blob->body, blob->next_free);
  if (blob_version == 0) {
    LOG(ERROR) << "Unknown or invalid blob version";
    return -1;
  }

  if (blob_version == 2) {
    buf += 4;
    remaining -= 4;
  }

  while (remaining >= 2) {
    uint32_t obj_size;
    uint32_t obj_type;
    size_t header_size;

    ReadObjectHeader(buf, remaining, blob_version, &obj_size, &obj_type,
                     &header_size);

    if (obj_size == 0) {
      break;  // Padding
    }
    if (obj_size > remaining) {
      LOG(ERROR) << "Object size exceeds remaining buffer size: " << obj_size
                 << " > " << remaining;
      return -1;
    }

    switch (obj_type) {
      case kPersoObjectTypeDeviceId: {
        if (ExtractDeviceId(buf, obj_size, blob_version, device_id) != 0) {
          LOG(ERROR) << "Failed to extract device ID";
          return -1;
        }
        break;
      }

      case kPersoObjectTypeX509Tbs: {
        if (*tbs_cert_count >= 10) {
          LOG(ERROR) << "Exceeded maximum number of TBS certificates";
          return -1;
        }
        perso_tlv_cert_obj_t cert_obj;
        if (ExtractCertObject(buf, obj_size, blob_version, &cert_obj) != 0) {
          LOG(ERROR) << "Failed to extract X509 TBS certificate object";
          return -1;
        }
        if (PackX509TbsCertStruct(&cert_obj, &tbs_certs[*tbs_cert_count]) !=
            0) {
          LOG(ERROR) << "Failed to pack TBS certificate endorsement request.";
          return -1;
        }
        (*tbs_cert_count)++;
        break;
      }

      case kPersoObjectTypeX509Cert:
      case kPersoObjectTypeCwtCert: {
        if (*cert_count >= 10) {
          LOG(ERROR) << "Exceeded maximum number of certificates";
          return -1;
        }
        perso_tlv_cert_obj_t cert_obj;
        if (ExtractCertObject(buf, obj_size, blob_version, &cert_obj) != 0) {
          LOG(ERROR) << "Failed to extract certificate object";
          return -1;
        }
        if (PackCertStruct(&cert_obj, obj_type, &certs[*cert_count]) != 0) {
          LOG(ERROR) << "Failed to pack certificate endorsement request.";
          return -1;
        }
        (*cert_count)++;
        break;
      }

      case kPersoObjectTypeWasTbsHmac: {
        memcpy(signature->raw, buf + header_size, sizeof(signature->raw));
        break;
      }

      case kPersoObjectTypeDevSeed:
      case kPersoObjectTypeGenericSeed: {
        if (*seed_count >= max_seed_count) {
          LOG(ERROR) << "Exceeded maximum number of seeds: " << *seed_count
                     << " >= " << max_seed_count;
          return -1;
        }
        seeds[*seed_count].size = obj_size - header_size;
        seeds[*seed_count].type = (uint16_t)obj_type;
        memcpy(seeds[*seed_count].raw, buf + header_size,
               seeds[*seed_count].size);
        (*seed_count)++;
        break;
      }

      case kPersoObjectTypePersoSha256Hash: {
        memcpy(perso_fw_hash->raw, buf + header_size,
               sizeof(perso_fw_hash->raw));
        break;
      }
    }

    buf += obj_size;
    remaining -= obj_size;
  }

  bool all_zero = true;
  for (size_t i = 0; i < sizeof(signature->raw); ++i) {
    if (signature->raw[i] != 0) {
      all_zero = false;
      break;
    }
  }
  if (all_zero) {
    LOG(ERROR) << "No WAS TBS HMAC found in the blob";
    return -1;
  }

  if (*tbs_cert_count == 0) {
    LOG(ERROR) << "No TBS certificates found in the blob";
    return -1;
  }
  uint32_t device_id_sum = 0;
  for (size_t i = 0; i < sizeof(device_id_bytes_t); i++) {
    device_id_sum += device_id->raw[i];
  }
  if (device_id_sum == 0) {
    LOG(ERROR) << "Device ID is empty";
    return -1;
  }

  return 0;
}

DLLEXPORT int PackPersoBlob(size_t cert_count,
                            const endorse_cert_response_t* certs,
                            size_t ca_cert_count,
                            const endorse_cert_response_t* ca_certs,
                            bool is_legacy_v1, perso_blob_t* blob) {
  if (blob == nullptr) {
    LOG(ERROR) << "Invalid personalization blob pointer";
    return -1;
  }
  if (cert_count == 0 || certs == nullptr) {
    LOG(ERROR) << "Invalid certificate count or certs pointer";
    return -1;
  }

  memset(blob, 0, sizeof(perso_blob_t));

  int blob_version = is_legacy_v1 ? 1 : 2;

  // Add Version Object for V2
  if (blob_version == 2) {
    uint8_t* buf = blob->body;
    uint16_t header = (kPersoObjectTypeBlobVersion << 12) | 4;
    *reinterpret_cast<uint16_t*>(buf) = __builtin_bswap16(header);
    *reinterpret_cast<uint16_t*>(buf + 2) = __builtin_bswap16(2);  // Version 2
    blob->next_free = 4;
    blob->num_objects = 1;
  }

  for (size_t i = 0; i < cert_count; i++) {
    if (PackCertTlvObject(&certs[i], blob_version, blob) != 0) {
      return -1;
    }
  }
  for (size_t i = 0; i < ca_cert_count; i++) {
    if (PackCertTlvObject(&ca_certs[i], blob_version, blob) != 0) {
      return -1;
    }
  }

  return 0;
}

DLLEXPORT int PackRegistryPersoTlvData(
    const endorse_cert_response_t* certs_endorsed_by_dut,
    size_t num_certs_endorsed_by_dut,
    const endorse_cert_response_t* certs_endorsed_by_spm,
    size_t num_certs_endorsed_by_spm, const seed_t* seeds, size_t num_seeds,
    bool is_legacy_v1, perso_blob_t* output) {
  if (output == nullptr) return -1;
  memset(output, 0, sizeof(perso_blob_t));

  int blob_version = is_legacy_v1 ? 1 : 2;

  // Add Version Object for V2
  if (blob_version == 2) {
    uint8_t* buf = output->body;
    uint16_t header = (kPersoObjectTypeBlobVersion << 12) | 4;
    *reinterpret_cast<uint16_t*>(buf) = __builtin_bswap16(header);
    *reinterpret_cast<uint16_t*>(buf + 2) = __builtin_bswap16(2);  // Version 2
    output->next_free = 4;
    output->num_objects = 1;
  }

  for (size_t i = 0; i < num_certs_endorsed_by_dut; i++) {
    if (PackCertTlvObject(&certs_endorsed_by_dut[i], blob_version, output) !=
        0) {
      return -1;
    }
  }
  for (size_t i = 0; i < num_certs_endorsed_by_spm; i++) {
    if (PackCertTlvObject(&certs_endorsed_by_spm[i], blob_version, output) !=
        0) {
      return -1;
    }
  }
  for (size_t i = 0; i < num_seeds; i++) {
    if (PackSeedTlvObject(&seeds[i], blob_version, output) != 0) {
      return -1;
    }
  }

  return 0;
}
