// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

package ate

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
)

// Constants from ate_api.h
const (
	kCertificateMaxSize         = 8192
	kCertificateKeyLabelMaxSize = 32
	kDevSeedBytesSize           = 128
	kWasHmacSignatureSize       = 32
	kPersoBlobMaxSize           = 65536
	kDeviceIDSize               = 32
)

// PersoObjectType represents the type of an object in a personalization blob.
type PersoObjectType uint16

// Constants from perso_tlv_data.h (via ate_perso_blob.h)
const (
	PersoObjectTypeX509Tbs     PersoObjectType = 0
	PersoObjectTypeX509Cert    PersoObjectType = 1
	PersoObjectTypeDevSeed     PersoObjectType = 2
	PersoObjectTypeCwtCert     PersoObjectType = 3
	PersoObjectTypeWasTbsHmac  PersoObjectType = 4
	PersoObjectTypeDeviceId    PersoObjectType = 5
	PersoObjectTypeGenericSeed PersoObjectType = 6
	PersoObjectTypeBlobVersion PersoObjectType = 15
)

const (
	sizeOfObjectHeaderV0 = 2
	sizeOfObjectHeaderV1 = 4
	sizeOfCertHeaderV0   = 2
	sizeOfCertHeaderV1   = 4

	v0HeaderSizeMask  = 0xFFF
	v0HeaderTypeShift = 12
	v1HeaderSizeMask  = 0xFFFFFF
	v1HeaderTypeShift = 24
	v1HeaderTypeMask  = 0xFF
)

// DeviceIDBytes corresponds to device_id_bytes_t
type DeviceIDBytes struct {
	Raw [kDeviceIDSize]byte
}

// EndorseCertSignature corresponds to endorse_cert_signature_t
type EndorseCertSignature struct {
	Raw [kWasHmacSignatureSize]byte
}

// EndorseCertRequest corresponds to endorse_cert_request_t
type EndorseCertRequest struct {
	KeyLabel string
	Tbs      []byte
}

// EndorseCertResponse corresponds to endorse_cert_response_t
type EndorseCertResponse struct {
	KeyLabel string
	Cert     []byte
}

// Seed corresponds to seed_t
type Seed struct {
	Type PersoObjectType
	Raw  []byte
}

// PersoBlob is the Go representation of the unpacked personalization blob.
type PersoBlob struct {
	DeviceID     *DeviceIDBytes
	Signature    *EndorseCertSignature
	X509TbsCerts []EndorseCertRequest
	X509Certs    []EndorseCertResponse
	Seeds        []Seed
	CwtCerts     []EndorseCertResponse
}

// persoTLVCertObj corresponds to perso_tlv_cert_obj_t
type persoTLVCertObj struct {
	CertBody []byte
	Name     string
}

func getObjectHeaderFields(body []byte, blobVersion int) (size uint32, objType PersoObjectType, headerSize int) {
	if blobVersion == 1 {
		header := binary.BigEndian.Uint32(body)
		size = header & v1HeaderSizeMask
		objType = PersoObjectType(header >> v1HeaderTypeShift)
		headerSize = sizeOfObjectHeaderV1
	} else {
		header := binary.BigEndian.Uint16(body)
		size = uint32(header & v0HeaderSizeMask)
		objType = PersoObjectType(header >> v0HeaderTypeShift)
		headerSize = sizeOfObjectHeaderV0
	}
	return
}

func getCertHeaderFields(body []byte, blobVersion int) (size uint32, nameSize uint32, headerSize int) {
	if blobVersion == 1 {
		header := binary.BigEndian.Uint32(body)
		size = header & v1HeaderSizeMask
		nameSize = header >> v1HeaderTypeShift
		headerSize = sizeOfCertHeaderV1
	} else {
		header := binary.BigEndian.Uint16(body)
		size = uint32(header & v0HeaderSizeMask)
		nameSize = uint32(header >> v0HeaderTypeShift)
		headerSize = sizeOfCertHeaderV0
	}
	return
}

func setObjectHeaderFields(buf []byte, size uint32, objType PersoObjectType, blobVersion int) int {
	if blobVersion == 1 {
		header := (uint32(objType&v1HeaderTypeMask) << v1HeaderTypeShift) | (size & v1HeaderSizeMask)
		binary.BigEndian.PutUint32(buf, header)
		return sizeOfObjectHeaderV1
	} else {
		header := (uint16(objType) << v0HeaderTypeShift) | uint16(size&v0HeaderSizeMask)
		binary.BigEndian.PutUint16(buf, header)
		return sizeOfObjectHeaderV0
	}
}

func setCertHeaderFields(buf []byte, certSize uint32, nameSize uint32, blobVersion int) int {
	if blobVersion == 1 {
		header := (nameSize << v1HeaderTypeShift) | (certSize & v1HeaderSizeMask)
		binary.BigEndian.PutUint32(buf, header)
		return sizeOfCertHeaderV1
	} else {
		header := uint16((nameSize << v0HeaderTypeShift) | (certSize & v0HeaderSizeMask))
		binary.BigEndian.PutUint16(buf, header)
		return sizeOfCertHeaderV0
	}
}

// IsLegacyV0Blob checks if a blob was generated by a legacy V0 firmware.
func IsLegacyV0Blob(body []byte) bool {
	if len(body) < 2 {
		return false
	}
	header := binary.BigEndian.Uint16(body[0:])
	return (header >> v0HeaderTypeShift) != uint16(PersoObjectTypeBlobVersion)
}

func getBlobVersion(body []byte) (int, error) {
	if len(body) < 2 {
		return -1, errors.New("unknown or invalid blob version")
	}
	header := binary.BigEndian.Uint16(body[0:])
	if (header >> v0HeaderTypeShift) == uint16(PersoObjectTypeBlobVersion) {
		return 1, nil
	}
	if IsLegacyV0Blob(body) {
		return 0, nil
	}
	return -1, errors.New("unknown or invalid blob version")
}

func extractCertObject(buf []byte, blobVersion int) (*persoTLVCertObj, error) {
	objSize, objType, headerSize := getObjectHeaderFields(buf, blobVersion)

	if objSize == 0 || int(objSize) > len(buf) {
		return nil, fmt.Errorf("invalid object size: %d, buffer size: %d", objSize, len(buf))
	}
	if objType != PersoObjectTypeX509Tbs && objType != PersoObjectTypeX509Cert && objType != PersoObjectTypeCwtCert {
		return nil, fmt.Errorf("invalid object type: %d, expected X509 TBS, cert, or CWT cert", objType)
	}

	buf = buf[headerSize:]
	certEntrySize, nameLen, certHeaderSize := getCertHeaderFields(buf, blobVersion)

	buf = buf[certHeaderSize:]
	if len(buf) < int(nameLen) {
		return nil, fmt.Errorf("buffer too small for certificate name: %d, available: %d", nameLen, len(buf))
	}

	name := string(buf[:nameLen])
	buf = buf[nameLen:]

	certBodySize := int(certEntrySize) - int(nameLen) - certHeaderSize
	if certBodySize < 0 {
		return nil, fmt.Errorf("invalid certificate body size: %d", certBodySize)
	}
	if len(buf) < certBodySize {
		return nil, fmt.Errorf("buffer too small for certificate body: %d, available: %d", certBodySize, len(buf))
	}

	return &persoTLVCertObj{
		Name:     name,
		CertBody: buf[:certBodySize],
	}, nil
}

// UnpackPersoBlob unpacks a raw personalization blob into a structured format.
// This is the Go equivalent of the C function with the same name.
func UnpackPersoBlob(blobBytes []byte) (*PersoBlob, error) {
	if len(blobBytes) == 0 {
		return nil, errors.New("invalid personalization blob: empty")
	}
	if len(blobBytes) > kPersoBlobMaxSize {
		return nil, fmt.Errorf("blob size %d exceeds max %d", len(blobBytes), kPersoBlobMaxSize)
	}

	blobVersion, err := getBlobVersion(blobBytes)
	if err != nil {
		return nil, err
	}

	persoBlob := &PersoBlob{}
	offset := 0

	if blobVersion == 1 {
		offset = sizeOfObjectHeaderV0 + 2 // V1 header (2 bytes) + 2 bytes version
	}

	for offset < len(blobBytes) {
		remaining := len(blobBytes[offset:])
		if remaining == 0 {
			break
		}
		if remaining < sizeOfObjectHeaderV0 {
			return nil, errors.New("remaining buffer too small for object header")
		}

		objSize, objType, headerSize := getObjectHeaderFields(blobBytes[offset:], blobVersion)

		if objSize == 0 {
			// Check if the rest of the buffer is zeroes (padding)
			for i := offset; i < len(blobBytes); i++ {
				if blobBytes[i] != 0 {
					return nil, fmt.Errorf("invalid object type %d with size 0", objType)
				}
			}
			break
		}
		if offset+int(objSize) > len(blobBytes) {
			return nil, fmt.Errorf("object size %d exceeds remaining buffer %d", objSize, len(blobBytes[offset:]))
		}

		objBytes := blobBytes[offset : offset+int(objSize)]

		switch objType {
		case PersoObjectTypeDeviceId:
			var deviceID DeviceIDBytes
			copy(deviceID.Raw[:], objBytes[headerSize:])
			persoBlob.DeviceID = &deviceID

		case PersoObjectTypeX509Tbs:
			certObj, err := extractCertObject(objBytes, blobVersion)
			if err != nil {
				return nil, fmt.Errorf("failed to extract X509 TBS cert: %w", err)
			}
			persoBlob.X509TbsCerts = append(persoBlob.X509TbsCerts, EndorseCertRequest{
				KeyLabel: certObj.Name,
				Tbs:      certObj.CertBody,
			})

		case PersoObjectTypeX509Cert:
			certObj, err := extractCertObject(objBytes, blobVersion)
			if err != nil {
				return nil, fmt.Errorf("failed to extract X509 cert: %w", err)
			}
			persoBlob.X509Certs = append(persoBlob.X509Certs, EndorseCertResponse{
				KeyLabel: certObj.Name,
				Cert:     certObj.CertBody,
			})
		case PersoObjectTypeCwtCert:
			certObj, err := extractCertObject(objBytes, blobVersion)
			if err != nil {
				return nil, fmt.Errorf("failed to extract CWT cert: %w", err)
			}
			persoBlob.CwtCerts = append(persoBlob.CwtCerts, EndorseCertResponse{
				KeyLabel: certObj.Name,
				Cert:     certObj.CertBody,
			})

		case PersoObjectTypeWasTbsHmac:
			var signature EndorseCertSignature
			copy(signature.Raw[:], objBytes[headerSize:])
			persoBlob.Signature = &signature

		case PersoObjectTypeDevSeed, PersoObjectTypeGenericSeed:
			seedData := objBytes[headerSize:]
			persoBlob.Seeds = append(persoBlob.Seeds, Seed{
				Type: objType,
				Raw:  seedData,
			})
		}
		offset += int(objSize)
	}

	return persoBlob, nil
}

// BuildPersoBlob serializes a PersoBlob struct into a byte slice.
func BuildPersoBlob(persoBlob *PersoBlob, isLegacyV0 bool) ([]byte, error) {
	var buf bytes.Buffer
	blobVersion := 1
	if isLegacyV0 {
		blobVersion = 0
	}

	// Add Version Object for V1
	if blobVersion == 1 {
		header := (uint16(PersoObjectTypeBlobVersion) << v0HeaderTypeShift) | uint16(4&v0HeaderSizeMask)
		hbuf := make([]byte, 2)
		binary.BigEndian.PutUint16(hbuf, header)
		buf.Write(hbuf)
		binary.BigEndian.PutUint16(hbuf, 1) // Version 1
		buf.Write(hbuf)
	}

	// 1. Device ID object
	if persoBlob.DeviceID != nil {
		headerSize := sizeOfObjectHeaderV1
		if blobVersion < 1 {
			headerSize = sizeOfObjectHeaderV0
		}
		objSize := uint32(headerSize + len(persoBlob.DeviceID.Raw))
		hbuf := make([]byte, 4)
		actualHeaderSize := setObjectHeaderFields(hbuf, objSize, PersoObjectTypeDeviceId, blobVersion)
		buf.Write(hbuf[:actualHeaderSize])
		buf.Write(persoBlob.DeviceID.Raw[:])
	}

	// 2. Signature object
	if persoBlob.Signature != nil {
		headerSize := sizeOfObjectHeaderV1
		if blobVersion < 1 {
			headerSize = sizeOfObjectHeaderV0
		}
		objSize := uint32(headerSize + len(persoBlob.Signature.Raw))
		hbuf := make([]byte, 4)
		actualHeaderSize := setObjectHeaderFields(hbuf, objSize, PersoObjectTypeWasTbsHmac, blobVersion)
		buf.Write(hbuf[:actualHeaderSize])
		buf.Write(persoBlob.Signature.Raw[:])
	}

	// 3. X509 TBS certificate objects
	for _, tbsCert := range persoBlob.X509TbsCerts {
		keyLabelBytes := []byte(tbsCert.KeyLabel)
		certHeaderSizeVal := sizeOfCertHeaderV1
		if blobVersion < 1 {
			certHeaderSizeVal = sizeOfCertHeaderV0
		}
		certEntrySize := uint32(certHeaderSizeVal + len(keyLabelBytes) + len(tbsCert.Tbs))
		headerSize := sizeOfObjectHeaderV1
		if blobVersion < 1 {
			headerSize = sizeOfObjectHeaderV0
		}
		objSize := uint32(headerSize) + certEntrySize
		hbuf := make([]byte, 4)
		actualHeaderSize := setObjectHeaderFields(hbuf, objSize, PersoObjectTypeX509Tbs, blobVersion)
		buf.Write(hbuf[:actualHeaderSize])

		actualCertHeaderSize := setCertHeaderFields(hbuf, certEntrySize, uint32(len(keyLabelBytes)), blobVersion)
		buf.Write(hbuf[:actualCertHeaderSize])
		buf.Write(keyLabelBytes)
		buf.Write(tbsCert.Tbs)
	}

	// 4. X509 certificate objects
	for _, cert := range persoBlob.X509Certs {
		keyLabelBytes := []byte(cert.KeyLabel)
		certHeaderSizeVal := sizeOfCertHeaderV1
		if blobVersion < 1 {
			certHeaderSizeVal = sizeOfCertHeaderV0
		}
		certEntrySize := uint32(certHeaderSizeVal + len(keyLabelBytes) + len(cert.Cert))
		headerSize := sizeOfObjectHeaderV1
		if blobVersion < 1 {
			headerSize = sizeOfObjectHeaderV0
		}
		objSize := uint32(headerSize) + certEntrySize
		hbuf := make([]byte, 4)
		actualHeaderSize := setObjectHeaderFields(hbuf, objSize, PersoObjectTypeX509Cert, blobVersion)
		buf.Write(hbuf[:actualHeaderSize])

		actualCertHeaderSize := setCertHeaderFields(hbuf, certEntrySize, uint32(len(keyLabelBytes)), blobVersion)
		buf.Write(hbuf[:actualCertHeaderSize])
		buf.Write(keyLabelBytes)
		buf.Write(cert.Cert)
	}

	// 5. CWT certificate objects
	for _, cert := range persoBlob.CwtCerts {
		keyLabelBytes := []byte(cert.KeyLabel)
		certHeaderSizeVal := sizeOfCertHeaderV1
		if blobVersion < 1 {
			certHeaderSizeVal = sizeOfCertHeaderV0
		}
		certEntrySize := uint32(certHeaderSizeVal + len(keyLabelBytes) + len(cert.Cert))
		headerSize := sizeOfObjectHeaderV1
		if blobVersion < 1 {
			headerSize = sizeOfObjectHeaderV0
		}
		objSize := uint32(headerSize) + certEntrySize
		hbuf := make([]byte, 4)
		actualHeaderSize := setObjectHeaderFields(hbuf, objSize, PersoObjectTypeCwtCert, blobVersion)
		buf.Write(hbuf[:actualHeaderSize])

		actualCertHeaderSize := setCertHeaderFields(hbuf, certEntrySize, uint32(len(keyLabelBytes)), blobVersion)
		buf.Write(hbuf[:actualCertHeaderSize])
		buf.Write(keyLabelBytes)
		buf.Write(cert.Cert)
	}

	// 6. Seed objects
	for _, seed := range persoBlob.Seeds {
		headerSize := sizeOfObjectHeaderV1
		if blobVersion < 1 {
			headerSize = sizeOfObjectHeaderV0
		}
		objSize := uint32(headerSize + len(seed.Raw))
		hbuf := make([]byte, 4)
		actualHeaderSize := setObjectHeaderFields(hbuf, objSize, seed.Type, blobVersion)
		buf.Write(hbuf[:actualHeaderSize])
		buf.Write(seed.Raw)
	}

	return buf.Bytes(), nil
}
