# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load(
    "//rules:hsm.bzl",
    "hsm_certgen",
    "hsm_certgen_tar",
    "hsm_certificate_authority_intermediate",
    "hsm_certificate_authority_intermediate_mldsa",
    "hsm_config_tar",
)
load(
    "//rules:hsmtool.bzl",
    "HSMTOOL_CONST",
)

package(default_visibility = ["//visibility:public"])

hsm_certificate_authority_intermediate(
    name = "ti01-ica-dice-key-p256-v0",
    curve = HSMTOOL_CONST.ECC_CURVE.PRIME256V1,
)

hsm_certificate_authority_intermediate_mldsa(
    name = "ti04-ica-dice-key-mldsa-v0",
)

hsm_certgen(
    name = "ti01_ca_int_dice",
    ca_key = "//config/spm/sku/eg/common:opentitan-ca-root-v0",
    config = ":ca_int_dice.conf",
    key = ":ti01-ica-dice-key-p256-v0",
)

hsm_certgen(
    name = "ti04_ca_int_dice",
    ca_key = "//config/spm/sku/eg/common:opentitan-mldsa-ca-root-v0",
    config = ":ca_int_dice.conf",
    key = ":ti04-ica-dice-key-mldsa-v0",
)

hsm_config_tar(
    name = "ti01_spm_ca_keygen",
    hsmtool_sequence = {
        ":ti01-ica-dice-key-p256-v0": "keygen",
    },
)

hsm_config_tar(
    name = "ti04_spm_ca_keygen",
    hsmtool_sequence = {
        ":ti04-ica-dice-key-mldsa-v0": "keygen",
    },
)

hsm_certgen_tar(
    name = "ti01_ca_intermediate_certgen",
    certs = [
        ":ti01_ca_int_dice",
    ],
)

hsm_certgen_tar(
    name = "ti04_ca_intermediate_certgen",
    certs = [
        ":ti04_ca_int_dice",
    ],
)

filegroup(
    name = "ti01_release",
    srcs = [
        ":ca_int_dice.conf",
        ":ti01_ca_intermediate_certgen",
        ":ti01_spm_ca_keygen",
    ],
)

filegroup(
    name = "ti04_release",
    srcs = [
        ":ca_int_dice.conf",
        ":ti04_ca_intermediate_certgen",
        ":ti04_spm_ca_keygen",
    ],
)
